services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev
      PGDATA: /data/postgres
    volumes:
      - c:/tmp/postgres_ostock:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ostock-network
    restart: unless-stopped


  configserver:
    container_name: configserver
    image: config-server:latest
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"
      EUREKA_HOST: "eureka"
    networks:
      - ostock-network


  licensing-service:
    image: licensing-service:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dockerdev"
      CONGIG_SERVER_HOST: configserver
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      - postgres
      - configserver
      - eureka
    networks:
      - ostock-network

  organization-service:
    image: organization-service:1.0
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "dockerdev"
      CONGIG_SERVER_HOST: configserver
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      - postgres
      - configserver
      - eureka
    networks:
      - ostock-network

  eureka:
    image: eureka:1.0
    ports:
      - "8070:8070"
    environment:
      CONGIG_SERVER_HOST: configserver
    depends_on:
      - configserver
    networks:
      - ostock-network

networks:
  ostock-network:

volumes:
  postgres: