services:
  postgres:
    container_name: postgres
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev
      PGDATA: /data/postgres
    volumes:
      - c:/tmp/postgres_ostock:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ostock-network
    restart: unless-stopped


  configserver:
    container_name: configserver
    image: config-server:1.0
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"
#      EUREKA_HOST: "eureka"
    networks:
      - ostock-network

  eurekaserver:
    container_name: eurekaserver
    image: eureka:1.0
    ports:
      - "8070:8070"
    environment:
      CONGIG_SERVER_HOST: configserver
      EUREKA_HOST: "eurekaserver"
    depends_on:
      - configserver
    networks:
      - ostock-network


  authorization-server:
    container_name: authorization-server
    image: auth-server:1.0
    ports:
      - "9999:9999"
    environment:
      SPRING_PROFILES_ACTIVE: "dockerdev"
      CONGIG_SERVER_HOST: configserver
      ENCRYPT_KEY: "IMSYMMETRIC"
      EUREKA_HOST: eurekaserver
    depends_on:
      - postgres
      - configserver
      - eurekaserver
    networks:
      - ostock-network
    restart: unless-stopped


  license-service:
    container_name: license-service
    image: license-service:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dockerdev"
      CONGIG_SERVER_HOST: configserver
      ENCRYPT_KEY: "IMSYMMETRIC"
      EUREKA_HOST: eurekaserver
    depends_on:
      - postgres
      - configserver
      - eurekaserver
    networks:
      - ostock-network
    restart: unless-stopped

  organization-service:
    container_name: organization-service
    image: organization-service:1.0
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "dockerdev"
      CONGIG_SERVER_HOST: configserver
      ENCRYPT_KEY: "IMSYMMETRIC"
      EUREKA_HOST: eurekaserver
    depends_on:
      - postgres
      - configserver
      - eurekaserver
    networks:
      - ostock-network
    restart: unless-stopped

  license-service-2:
    container_name: license-service-2
    image: license-service:1.0
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dockerdev"
      CONGIG_SERVER_HOST: configserver
      ENCRYPT_KEY: "IMSYMMETRIC"
      EUREKA_HOST: eurekaserver
    depends_on:
      - postgres
      - configserver
      - eurekaserver
    networks:
      - ostock-network
    restart: unless-stopped


  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      backend:
        aliases:
          - "zookeeper"
  kafkaserver:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper
    networks:
      backend:
        aliases:
          - "kafka"
  redisserver:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      backend:
        aliases:
          - "redis"


networks:
  ostock-network:
  backend:
volumes:
  postgres: